<?php

// Define the exception strings to be used here
define('PAGE_NOT_FOUND_ACTION', '404ACTION');

//Define admin actions
define('DISPLAY_ADMIN_LOGIN_PAGE_ACTION', 'SHOW_LOGIN_PAGE');
define('AUTHENTICATE_ADMIN_USER_ACTION', 'AUTH_ADMIN_USER');
define('PASSWORD_RESET_PAGE_ACTION', 'SHOW_PASSWORD_RESET_PAGE');
define('SHOW_ADMIN_DASHBOARD_ACTION', 'SHOW_ADMIN_DASHBOARD');
define('LOAD_BLOG_EDIT_ACTION', 'SHOW_BLOG_EDIT');
define('SET_NEW_PASSWORD_PAGE', 'SHOW_SET_NEW_PASSWORD');

//Admin components
define('LOAD_BLOG_EDIT_PANEL_ACTION', 'LOAD_BLOG_EDIT_PANEL');
define('BLOG_SEARCH_PANEL_ACTION', 'LOAD_BLOG_SEARCH_PANEL');

//Admin AJAX actions
define('AJAX_ADMIN_AUTH_USER_ACTION', 'ADMIN_AUTH_USER');
define('AJAX_ADMIN_SAVE_BLOG_ACTION', 'ADMIN_SAVE_BLOG');
define('AJAX_ADMIN_DELETE_BLOG_ACTION', 'ADMIN_DELETE_BLOG');
define('AJAX_ADMIN_SEARCH_BLOGS', 'ADMIN_SEARCH_BLOGS');
define('AJAX_ADMIN_BLOG_MEDIA_UPLOAD', 'ADMIN_BLOG_MEDIA_UPLOAD');
define('AJAX_ADMIN_LOGOUT_ACTION', 'LOGOUT');
define('AJAX_ADMIN_PASSWORD_RESET', 'PASSWORD_RESET');
define('AJAX_ADMIN_SET_NEW_PASSWORD', 'AJAX_ADMIN_SET_NEW_PASSWORD');

//Define static actions
define('FETCH_GENERAL_STATIC_ACTION', 'GENERAL_STATIC');
define('FETCH_CSS_ACTION', 'CSS');
define('FETCH_JS_ACTION', 'JS');
define('FETCH_ADMIN_STATIC_ACTION', 'GENERAL_ADMIN_STATIC');
define('FETCH_ADMIN_CSS_ACTION', 'ADMIN_CSS');
define('FETCH_ADMIN_JS_ACTION', 'ADMIN_JS');
define('FETCH_BLOGPOST_STATIC', 'BLOGPOST_STATIC');

// Blog actions here
define('FETCH_HOME_PAGE', 'FETCH_HOME_PAGE');
define('FETCH_COVER_PAGE', 'FETCH_COVER_PAGE');

// Here is a test action to help me to build shit
define('TEST_ACTION', 'TEST_ACTION');
define('PHP_INFO', 'PHP_INFO');
